# Generated by Django 5.2 on 2025-04-25 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_booking_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='education',
            field=models.TextField(blank=True, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='experience years'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price per hour'),
        ),
    ]
